name: data-warehouse
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - awswrangler=3.4.1
  - boto3=1.28.70
  - botocore=1.31.70
  - ipython-sql=0.3.9
  - jupyter=1.0.0
  - pandas=2.1.1
  - pip=23.3.1
  - prettytable=3.9.0
  - psycopg2=2.9.7
  - psycopg2-binary=2.9.7
  - sqlalchemy=1.4.49
  - pip:
    - python-dotenv==1.0.0